export interface Thema {
  id: string;
  titel: string;
  emoji: string;
  kategorie: "fahrzeug" | "haus" | "finanzen" | "community" | "wissen";
  kurztext: string;
  detailtext: string;
  level: 0 | 1 | 2 | 3;
  farbe: string;
}

export const themen: Thema[] = [
  {
    id: "svenflex",
    titel: "Svenflex — Mobiles Strömungssystem",
    emoji: "⚡",
    kategorie: "fahrzeug",
    level: 0,
    farbe: "from-cyan-500 to-blue-600",
    kurztext: "Das mobile Strömungsoptimierungssystem für dein Auto. Weniger Verbrauch, mehr Leistung — einstecken, fertig.",
    detailtext: "Svenflex ist das mobile System, das du selbst ein- und ausbauen kannst. Geeignet für Benzin & Diesel. Über 500 verkaufte Systeme. Bewiesen auf Rennstrecke, Prüfstand und im Alltagstest. Provision: 250€ pro Empfehlung.",
  },
  {
    id: "stropt-fix",
    titel: "Sventronik Fix — Festeinbau System",
    emoji: "🔧",
    kategorie: "fahrzeug",
    level: 0,
    farbe: "from-blue-600 to-indigo-700",
    kurztext: "Das professionelle Festeinbau-System für maximale Effizienz. VIP-Einbau durch geschulten Partner inklusive.",
    detailtext: "Das Sventronik Fix System (1.990€) wird von einem VIP-Einbaupartner direkt bei dir vor Ort eingebaut. Inklusive Probefahrt vor und nach der Installation. Du erhältst eine Einbau-Schulung und wirst Teil des Partnerprogramms: 200€ pro Empfehlung + 200€ pro Einbau.",
  },
  {
    id: "svenfix-vip",
    titel: "Svenfix VIP Einbau Service",
    emoji: "🏆",
    kategorie: "fahrzeug",
    level: 1,
    farbe: "from-yellow-500 to-orange-600",
    kurztext: "Ein geschulter Partner kommt zu dir. Einbau, Probefahrt, Optimierung — alles vor Ort.",
    detailtext: "Wert: 300€. Ein von Sven geschulter Einbaupartner kommt direkt zu dir, baut das System ein inkl. Probefahrt vor und nach Installation. Geheime Optimierungen die das System gegenüber Hersteller-Variante deutlich steigern (Systembooster, Wert 500€). Danach kannst du selbst Einbauten vornehmen und 200€ pro Einbau verdienen.",
  },
  {
    id: "wasserstoff-auto",
    titel: "Wasserstoff im Auto",
    emoji: "🚗",
    kategorie: "fahrzeug",
    level: 1,
    farbe: "from-teal-500 to-cyan-600",
    kurztext: "Wasserstoff als Kraftstoff direkt im Verbrennungsmotor — die Technologie der Zukunft, heute verfügbar.",
    detailtext: "Das Wasserstoff-im-Auto Paket ist exklusiv für Inner Circle Mitglieder. Details zu Technik, Bezugsquellen und Installation nach Freischaltung.",
  },
  {
    id: "wasserstoff-heizung",
    titel: "Wasserstoff-Heizung V3",
    emoji: "🔥",
    kategorie: "haus",
    level: 2,
    farbe: "from-orange-500 to-red-600",
    kurztext: "Die neue Version der Wasserstoff-Heizung — präsentiert im Europäischen Wasserstoff- und Innovationszentrum.",
    detailtext: "Die Wasserstoff-Heizung V3 wird im entstehenden Europäischen Wasserstoff- und Innovationszentrum vorgestellt. Alle Details, Preise und Verfügbarkeit exklusiv für Inner Circle Mitglieder (Level 3).",
  },
  {
    id: "autarke-stromerzeugung",
    titel: "Autarke Stromerzeugung",
    emoji: "☀️",
    kategorie: "haus",
    level: 2,
    farbe: "from-yellow-400 to-green-500",
    kurztext: "Energetische Autarkie — dein Zuhause produziert mehr Energie als es verbraucht.",
    detailtext: "Ein Prototyp für vollständige energetische Autarkie wird im Europäischen Innovationszentrum präsentiert. Das Ziel: Alle Energie-Technologien refinanzieren sich selbst über monatliche Raten.",
  },
  {
    id: "stroemungsoptimierung-lkw",
    titel: "Strömungsoptimierung Flotten & LKW",
    emoji: "🚚",
    kategorie: "fahrzeug",
    level: 1,
    farbe: "from-slate-500 to-gray-700",
    kurztext: "Für Flottenbetreiber und LKW-Fahrer. Bewiesene 26% Verbrauchsreduktion bei Betonmischer-Flotte.",
    detailtext: "300 Betonmischer-Flotte: 100 mit Technik ausgestattet → 26% weniger Verbrauch. Schwere LKW erhalten offizielle Förderung (Reibungsreduzierung). LKW-Prüfstand: 5% Verbrauchsersparnis nachweislich belegt.",
  },
  {
    id: "motorrad",
    titel: "Strömungsoptimierung Motorrad",
    emoji: "🏍️",
    kategorie: "fahrzeug",
    level: 0,
    farbe: "from-purple-500 to-pink-600",
    kurztext: "Für Motorräder — Labortest zeigt signifikant reduzierte Vibrationen und optimierten Kraftstofffluss.",
    detailtext: "Im Labor nachgewiesene Vibrations-Reduktion. Spezifische Einbauanleitung und Produktvariante für Motorräder. Details nach Kauf verfügbar.",
  },
  {
    id: "probefahrt-netzwerk",
    titel: "Probefahrt-Netzwerk",
    emoji: "🗺️",
    kategorie: "community",
    level: 1,
    farbe: "from-green-500 to-emerald-600",
    kurztext: "92 Svenflex-Partner in DE, CH, AT. Jeder Interessent kann eine Probefahrt in seiner Nähe buchen.",
    detailtext: "Als Svenflex-Käufer wirst du automatisch Probefahrt-Partner. Deine PLZ wird anonym in der Karte eingetragen. Interessenten anfragen direkt bei dir an. Das Netzwerk wächst — aktuell 78 Partner in Deutschland, 8 in der Schweiz, 4 in Österreich.",
  },
  {
    id: "partnerprogramm",
    titel: "Partnerprogramm & Provisionen",
    emoji: "🤝",
    kategorie: "community",
    level: 1,
    farbe: "from-blue-400 to-cyan-500",
    kurztext: "Empfehle das System und verdiene: 250€ für Svenflex, 200€ für Fix-System, 200€ pro Einbau.",
    detailtext: "Provisionsstruktur: Svenflex mobil: 250€ | STROPT Festsystem: 200€ | VIP Einbaupartner: zusätzlich 200€ pro Einbau. Ein Dutzend Empfehlungen/Einbauten = mittlerer 4-stelliger Zusatzverdienst. Auszahlung via Wallet-ID auf dein dezentrales Konto.",
  },
  {
    id: "inner-circle",
    titel: "Inner Circle",
    emoji: "👑",
    kategorie: "community",
    level: 3,
    farbe: "from-yellow-400 to-amber-600",
    kurztext: "Die Inner Circle Sprechstunde findet jeden Donnerstag um 19:15 Uhr statt. Exklusiver Zugang zu allen Technologien.",
    detailtext: "Inner Circle Mitglieder erhalten Zugang zu Wasserstoff-Heizung, Wasserstoff-im-Auto, autarker Stromerzeugung und allen zukünftigen Technologien. Wöchentliche Live-Sprechstunde. Direkter Kontakt zu Sven.",
  },
  {
    id: "dezentrale-finanzen",
    titel: "Dezentrale Finanzen",
    emoji: "💎",
    kategorie: "finanzen",
    level: 1,
    farbe: "from-violet-500 to-purple-700",
    kurztext: "Dezentrales Konto ohne Behördenzugriff. Kein Einfrieren. Keine Dritte-Partei-Kontrolle.",
    detailtext: "Im Offer Stack enthalten: Dezentrales Konto (250$ Guthaben, 10% monatliche Ausschüttung) + Krypto-Kurs von Tim Stern (cryptochampion.de, Wert 999€). Das System refinanziert sich schrittweise selbst.",
  },
  {
    id: "refi-prinzip",
    titel: "Das Selbst-Refinanzierungs-Prinzip",
    emoji: "🔄",
    kategorie: "finanzen",
    level: 0,
    farbe: "from-emerald-500 to-teal-600",
    kurztext: "Alle Energie-Technologien refinanzieren sich über monatliche Raten selbst. Das System zahlt sich bezahlt.",
    detailtext: "5x447€ Raten oder einmalig 2.197€. Gesamtwert: 5.486€. Einbau nach 4 Wochen (nach 2. Rate). Das dezentrale Konto schüttet 10% monatlich aus — bis das System vollständig refinanziert ist.",
  },
  {
    id: "offer-stack",
    titel: "Der komplette Offer Stack",
    emoji: "📦",
    kategorie: "finanzen",
    level: 0,
    farbe: "from-pink-500 to-rose-600",
    kurztext: "Gesamtwert 5.486€ für 2.197€ oder 5x447€. Fix System + VIP Einbau + Booster + Schulung + Krypto + Inner Circle.",
    detailtext: "Fix System Diesel/Benzin 1.990€ | VIP Installation 300€ | System Booster 500€ | Partner Schulung 480€ | Krypto-Konto 250$ | Krypto-Kurs 999€ | 12 Monate Inner Circle 997€. Gesamtwert: 5.486€.",
  },
  {
    id: "energy-sovereignty",
    titel: "Energy Sovereignty System™",
    emoji: "🌍",
    kategorie: "wissen",
    level: 0,
    farbe: "from-cyan-400 to-blue-500",
    kurztext: "Die übergeordnete Kategorie. Kein Verbesserungs-Angebot — eine komplett neue Kategorie für energetische, finanzielle und persönliche Freiheit.",
    detailtext: "Energie-Souveränität = Freiheit. Vehicle: das Energy Sovereignty System™. Zielgruppe: Energie-Freigeister. Ziel: energetische + finanzielle + persönliche Freiheit. Kein Improvement Offer — New Opportunity nach Russell Brunson.",
  },
  {
    id: "beweise-technik",
    titel: "Die 7 Praxis-Beweise",
    emoji: "🔬",
    kategorie: "wissen",
    level: 0,
    farbe: "from-indigo-500 to-blue-700",
    kurztext: "Rennstrecke. Prüfstand. Magazin-Test. Labor. Flotte. Förderung. Windkanal. 7 unabhängige Beweise.",
    detailtext: "1. Auto von letztem auf ersten Platz in 2 Runden (Rennstrecke). 2. LKW-Prüfstand: 5% weniger Verbrauch. 3. Reifen-Test Magazin: eine Schulnote besser. 4. Motorrad-Labor: Vibrationen signifikant reduziert. 5. 300 Betonmischer, 100 ausgestattet: 26% weniger. 6. LKW Förderung offiziell. 7. Windkanal-Doppelflügel.",
  },
  {
    id: "svens-story",
    titel: "Svens Geschichte",
    emoji: "📖",
    kategorie: "wissen",
    level: 0,
    farbe: "from-amber-500 to-orange-600",
    kurztext: "Wie Sven Mund die Strömungsoptimierung entdeckte, über 500 Systeme verkaufte und was er daraus lernte.",
    detailtext: "Sven lernte die Strömungsoptimierung durch einen Hinweis aus seiner Wasserstoff-Community kennen. Er entwickelte eine klare Produktstrategie: 1 Produkt statt 5-7, klare Preisstruktur, Empfehlungsnetzwerk. Innerhalb von etwas mehr als einem Jahr: über 500 verkaufte Systeme.",
  },
  {
    id: "europaeisches-innovationszentrum",
    titel: "Europäisches Wasserstoff- & Innovationszentrum",
    emoji: "🏛️",
    kategorie: "wissen",
    level: 0,
    farbe: "from-blue-500 to-teal-500",
    kurztext: "Das entstehende Zentrum für alle Energie-Technologien. Hier wird die Wasserstoff-Heizung V3 präsentiert.",
    detailtext: "Das Europäische Wasserstoff- und Innovationszentrum entsteht als physischer Ankerpunkt für alle Energie-Technologien. Prototyp für energetische Autarkie. Wasserstoff-Heizung V3 Live-Präsentation. Partner und Inner Circle Mitglieder erhalten exklusiven Zugang.",
  },
  {
    id: "svens-buch-stroemung",
    titel: "Buch: Strömungsoptimierung",
    emoji: "📚",
    kategorie: "wissen",
    level: 0,
    farbe: "from-gray-600 to-slate-700",
    kurztext: "Das vollständige Wissen zur Strömungsoptimierung — Technik, Beweise, Einbau, Optimierungen.",
    detailtext: "Svens Buch zur Strömungsoptimierung erscheint in Kürze. Als Inner Circle Mitglied erhältst du es als Erster. Inhalt: Technik, alle 7 Praxis-Beweise, Einbauanleitung, Optimierungsgeheimnisse.",
  },
  {
    id: "webinar-stroemung",
    titel: "Webinar: Das Energy Sovereignty System™",
    emoji: "🎥",
    kategorie: "wissen",
    level: 0,
    farbe: "from-red-500 to-rose-700",
    kurztext: "Svens Live-Webinar — Technik, Story, Beweise, Offer Stack und Q&A. Aufzeichnung verfügbar.",
    detailtext: "Im Webinar stellt Sven das komplette Energy Sovereignty System™ vor: Die Geschichte, die 7 Beweise, den Offer Stack und wie sich das System selbst refinanziert. Aufzeichnung für alle Level-0+ Nutzer verfügbar.",
  },
  {
    id: "donnerstags-sprechstunde",
    titel: "Inner Circle Sprechstunde",
    emoji: "📅",
    kategorie: "community",
    level: 3,
    farbe: "from-violet-600 to-indigo-700",
    kurztext: "Jeden Donnerstag, 19:15 Uhr. Live mit Sven. Fragen, Updates, neue Technologien.",
    detailtext: "Die wöchentliche Inner Circle Sprechstunde ist das Herzstück der Community. Jeden Donnerstag um 19:15 Uhr. Direkter Austausch mit Sven. Neue Technologien, Strategien und Möglichkeiten werden hier zuerst vorgestellt.",
  },
  {
    id: "klima-klarheit",
    titel: "14-Tage-Klarheits-Garantie",
    emoji: "✅",
    kategorie: "finanzen",
    level: 0,
    farbe: "from-green-400 to-emerald-600",
    kurztext: "Bestelle — teste 14 Tage — oder Geld zurück. Kein Risiko, volle Transparenz.",
    detailtext: "Die 14-Tage-Klarheits-Garantie (Frühe Entscheidungs-Garantie): Du hast 14 Tage Zeit, das System zu testen. Wenn du nicht überzeugt bist, erhältst du den vollen Betrag zurück. Kein Kleingedrucktes.",
  },
];

export const kategorien = [
  { id: "alle", label: "Alle Themen", emoji: "🌐" },
  { id: "fahrzeug", label: "Fahrzeug", emoji: "🚗" },
  { id: "haus", label: "Haus & Energie", emoji: "🏠" },
  { id: "finanzen", label: "Finanzen", emoji: "💰" },
  { id: "community", label: "Community", emoji: "👥" },
  { id: "wissen", label: "Wissen", emoji: "📖" },
];
